import os
import re
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

def set_cell_border(cell, **kwargs):
    """
    Set cell borders
    Usage: set_cell_border(cell, top={"sz": 12, "val": "single", "color": "#FF0000", "space": "0"}, ...)
    """
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    for side in ("top", "left", "bottom", "right"):
        if side in kwargs:
            tag = 'w:{}'.format(side)
            element = tcPr.find(qn(tag))
            if element is not None:
                tcPr.remove(element)
            element = OxmlElement(tag)
            for key, value in kwargs[side].items():
                element.set(qn('w:{}'.format(key)), str(value))
            tcPr.append(element)

def create_formal_docx(title, content_markdown, output_path):
    """
    Creates a high-fidelity formal DOCX file from markdown.
    Handles headers, lists, tables, and bold text.
    """
    doc = Document()
    
    # Page setup
    section = doc.sections[0]
    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(1.0)
    section.right_margin = Inches(1.0)
    
    # Default style
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'
    font.size = Pt(11)
    
    # Add Header
    header = section.header
    hp = header.paragraphs[0]
    hp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = hp.add_run("NPCI | CONFIDENTIAL | UPI TITANS")
    run.font.size = Pt(9)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x3B, 0x82, 0xF6) # Blue
    
    # Add Footer with Page Number
    footer = section.footer
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = fp.add_run("PROPRIETARY & CONFIDENTIAL - NPCI")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x94, 0xA3, 0xB8) # Slate
    
    # Add Stylish Title
    doc.add_paragraph()
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run(title.upper())
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B) # Slate 900
    
    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle_p.add_run("Generated by Titan Orchestration Engine")
    run.font.size = Pt(10)
    run.italic = True
    run.font.color.rgb = RGBColor(0x63, 0x66, 0xF1) # Indigo 500
    
    doc.add_paragraph()
    doc.add_paragraph()
    
    doc.add_paragraph()
    doc.add_paragraph()
    
    # Metadata Table
    meta_table = doc.add_table(rows=3, cols=2)
    meta_table.style = 'Table Grid'
    meta_table.columns[0].width = Inches(1.5)
    meta_table.columns[1].width = Inches(4.5)
    
    metadata = [
        ("Version", "1.0 (PROVISIONED)"),
        ("Date", "March 26, 2026"),
        ("Status", "DRAFT_INTERNAL")
    ]
    
    for idx, (lbl, val) in enumerate(metadata):
        row = meta_table.rows[idx]
        row.cells[0].text = lbl
        row.cells[1].text = val
        row.cells[0].paragraphs[0].runs[0].bold = True
        # Faint background for label cell
        tc = row.cells[0]._tc
        tcPr = tc.get_or_add_tcPr()
        shd = OxmlElement('w:shd')
        shd.set(qn('w:fill'), 'F8FAFC') # Very light slate
        tcPr.append(shd)

    doc.add_paragraph()
    doc.add_paragraph()
    
    lines = content_markdown.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        if not line:
            doc.add_paragraph()
            i += 1
            continue
            
        # Table Detection
        if line.startswith('|') and i + 1 < len(lines) and lines[i+1].strip().startswith('|---'):
            # Parse table
            table_lines = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                table_lines.append(lines[i].strip())
                i += 1
            
            if len(table_lines) >= 3: # header, divider, at least one row
                header_row = [cell.strip() for cell in table_lines[0].split('|') if cell.strip()]
                data_rows = []
                for row_line in table_lines[2:]: # Ship divider
                    data_rows.append([cell.strip() for cell in row_line.split('|') if cell.strip()])
                
                table = doc.add_table(rows=1, cols=len(header_row))
                table.style = 'Table Grid'
                hdr_cells = table.rows[0].cells
                for idx, text in enumerate(header_row):
                    hdr_cells[idx].text = text
                    # Bold header
                    for p in hdr_cells[idx].paragraphs:
                        for r in p.runs:
                            r.bold = True
                    # Background color for header (faint gracy)
                    tc = hdr_cells[idx]._tc
                    tcPr = tc.get_or_add_tcPr()
                    shd = OxmlElement('w:shd')
                    shd.set(qn('w:fill'), 'F2F2F2')
                    tcPr.append(shd)

                for row_data in data_rows:
                    row_cells = table.add_row().cells
                    for idx, text in enumerate(row_data):
                        if idx < len(row_cells):
                            row_cells[idx].text = text
            continue

        # Regular Markdown elements
        if line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('- ') or line.startswith('* '):
            p = doc.add_paragraph(style='List Bullet')
            parse_formatting(p, line[2:])
        elif re.match(r'^\d+\. ', line):
            p = doc.add_paragraph(style='List Number')
            parse_formatting(p, re.sub(r'^\d+\. ', '', line))
        else:
            p = doc.add_paragraph()
            parse_formatting(p, line)
        
        i += 1
                    
    doc.save(output_path)
    return output_path

def parse_formatting(paragraph, text):
    """Parses bold and italic in a paragraph."""
    # Bold: **text**
    # Italic: *text* (very simple)
    parts = re.split(r'(\*\*.*?\*\*|\*.*?\*)', text)
    for part in parts:
        if part.startswith('**') and part.endswith('**'):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith('*') and part.endswith('*'):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        else:
            paragraph.add_run(part)

import re # already imported but for safety
